name: generate_routines
on:
    schedule:
    - cron: '0 0 * * *'
    workflow_dispatch:
jobs:
  update_plot:
    name: Generate Routine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            token:
                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
        
        
      - name: Setup Python
        uses: actions/setup-python@v2
        
        with:
          python-version: '3.8'
          cache: 'pip'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt
        
        
      - name: Run Script and Update Plot
        run: |
          jupyter nbconvert --to script Prototype_Final_(Working).ipnyb
          python pPrototype_Final_(Working).py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "vibumy@gmail.com"
          git config --local user.name "Github Actions"
          git add truck_manager_merged_df.csv
          git commit -m "updates routing"
          git push 
